### ISSUE TITLE
where is tqdm module?

### ISSUE THREAD

**Issue by joyivan** [FateScript/cifar_resnet#1]
I thinks the author can not upload the file tqdm.py .

> Traceback (most recent call last):
>   File "drop.py", line 7, in <module>
>     from tqdm import tqdm
> ImportError: No module named tqdm

**Comment by FateScript** [comment]
> I thinks the author can not upload the file tqdm.py .
> 
> > Traceback (most recent call last):
> > File "drop.py", line 7, in 
> > from tqdm import tqdm
> > ImportError: No module named tqdm

**Comment by FateScript** [comment]
> I thinks the author can not upload the file tqdm.py .
> 
> > Traceback (most recent call last):
> > File "drop.py", line 7, in 
> > from tqdm import tqdm
> > ImportError: No module named tqdm

You may use "pip install" command to install tqdm module

**Comment by joyivan** [comment]
> > I thinks the author can not upload the file tqdm.py .
> > > Traceback (most recent call last):
> > > File "drop.py", line 7, in
> > > from tqdm import tqdm
> > > ImportError: No module named tqdm
> 
> You may use "pip install" command to install tqdm module

Thank a lot ....  thank you, I have no idea that tqdm was a module can pip install.
